# LNN 3-Stage Pipeline Evaluation
## Stage 1 (LOS/NLOS) → Stage 2 (Correctable?) → Stage 3 (bounce_path_idx → d_bounce)

**Purpose**: Evaluate the full chained LNN pipeline on held-out test data.

**Key design**: One global 70/15/15 split (from Stage 1) governs combined dataset.
- Stage 2 RF trained on `idx_train` NLOS embeddings (70%) — 64 features
- Stage 3 RF trained on `idx_train` correctable NLOS — 66 features (64 LNN + fp_idx + d_hw)
- All stages trained on combined dataset only

**Stage 3 formulation**:
- Target: `bounce_path_idx = fp_idx + (d_bounce − d_hardware) / 0.3003` — per-sample continuous CIR index
- Inverse: `d_bounce = d_hardware + (predicted_bpi − fp_idx) × 0.3003` — convert back to meters
- Why: d_bounce is constant per scenario → regressing a constant is meaningless. bounce_path_idx varies per sample (fp_idx, d_hardware differ) → real regression.

**Architecture**: DualCircuit_PI_HLNN_NoFP (v3) — No FP_AMPL conditioning, zero-init h₀

**Artifacts loaded**:
- `stage1_pi_hlnn_no_fp_v3_best.pt` — Frozen encoder + classifier

**Trained in this notebook**:
- Stage 2 RF Classifier (correctable vs challenging) — on `idx_train` NLOS (64 features)
- Stage 3 RF Regressor (bounce_path_idx) — on `idx_train` correctable NLOS (66 features)

In [62]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import torch
import torch.nn as nn
import torch.nn.functional as F
import re
import os
from scipy.signal import find_peaks
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier, RandomForestRegressor
from sklearn.metrics import (
    mean_absolute_error, mean_squared_error, r2_score,
    confusion_matrix, ConfusionMatrixDisplay, roc_curve, auc,
    classification_report, precision_score, recall_score, f1_score, accuracy_score
)

M_PER_IDX = 0.3003
DIST_PER_IDX = 0.3002

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(f"Device: {device}")

Device: cuda

---
## Section 1: Model Definition + Load Stage 1 Encoder

DualCircuit_PI_HLNN_NoFP (v3): No FP_AMPL conditioning, zero-init h₀, average pooling.

In [63]:
# ==========================================
# MODEL DEFINITION (identical to Stage 1/2/3)
# ==========================================
class PILiquidCell(nn.Module):
    """Conductance-based LTC cell (Hasani et al. 2020)."""
    def __init__(self, input_size, hidden_size, ode_unfolds=6):
        super().__init__()
        self.hidden_size = hidden_size
        self.input_size = input_size
        self.ode_unfolds = ode_unfolds

        self.gleak = nn.Parameter(torch.empty(hidden_size).uniform_(0.001, 1.0))
        self.vleak = nn.Parameter(torch.empty(hidden_size).uniform_(-0.2, 0.2))
        self.cm    = nn.Parameter(torch.empty(hidden_size).uniform_(0.4, 0.6))

        self.w     = nn.Parameter(torch.empty(hidden_size, hidden_size).uniform_(0.001, 1.0))
        self.erev  = nn.Parameter(torch.empty(hidden_size, hidden_size).uniform_(-0.2, 0.2))
        self.mu    = nn.Parameter(torch.empty(hidden_size, hidden_size).uniform_(0.3, 0.8))
        self.sigma = nn.Parameter(torch.empty(hidden_size, hidden_size).uniform_(3, 8))

        self.sensory_w     = nn.Parameter(torch.empty(input_size, hidden_size).uniform_(0.001, 1.0))
        self.sensory_mu    = nn.Parameter(torch.empty(input_size, hidden_size).uniform_(0.3, 0.8))
        self.sensory_sigma = nn.Parameter(torch.empty(input_size, hidden_size).uniform_(3, 8))

    def forward(self, x_t, h_prev, dt=1.0):
        gleak     = F.softplus(self.gleak)
        cm        = F.softplus(self.cm)
        w         = F.softplus(self.w)
        sensory_w = F.softplus(self.sensory_w)

        sensory_gate    = torch.sigmoid(self.sensory_sigma * (x_t.unsqueeze(-1) - self.sensory_mu))
        sensory_current = (sensory_w * sensory_gate * x_t.unsqueeze(-1)).sum(dim=1)

        cm_t = cm / (dt / self.ode_unfolds)
        v    = h_prev

        for _ in range(self.ode_unfolds):
            recurrent_gate = torch.sigmoid(self.sigma.unsqueeze(0) * (v.unsqueeze(2) - self.mu.unsqueeze(0)))
            w_gate = w.unsqueeze(0) * recurrent_gate
            w_num  = (w_gate * self.erev.unsqueeze(0)).sum(dim=1)
            w_den  = w_gate.sum(dim=1)
            numerator   = cm_t * v + gleak * self.vleak + w_num + sensory_current
            denominator = cm_t + gleak + w_den + 1e-8
            v = numerator / denominator
            v = torch.clamp(v, -1.0, 1.0)

        tau = cm / (gleak + w_den + 1e-8)
        return v, tau


class DualCircuit_PI_HLNN_NoFP(nn.Module):
    """Dual-circuit PI-HLNN WITHOUT FP_AMPL conditioning (v3). Zero-init h0."""
    def __init__(self, input_size=1, hidden_size=32, dropout=0.2, ode_unfolds=6):
        super().__init__()
        self.hidden_size = hidden_size

        self.cell_los  = PILiquidCell(input_size, hidden_size, ode_unfolds)
        self.cell_nlos = PILiquidCell(input_size, hidden_size, ode_unfolds)

        self.P_nlos2los = nn.Linear(hidden_size, hidden_size, bias=False)
        self.P_los2nlos = nn.Linear(hidden_size, hidden_size, bias=False)

        self.gate_los  = nn.Linear(hidden_size * 2, hidden_size)
        self.gate_nlos = nn.Linear(hidden_size * 2, hidden_size)

        self.classifier = nn.Sequential(
            nn.Linear(hidden_size * 2, hidden_size),
            nn.SiLU(),
            nn.Dropout(dropout),
            nn.Linear(hidden_size, 1),
            nn.Sigmoid()
        )

    def _run_circuits(self, x_seq):
        batch_size, seq_len, _ = x_seq.size()
        h_los  = torch.zeros(batch_size, self.hidden_size, device=x_seq.device)
        h_nlos = torch.zeros(batch_size, self.hidden_size, device=x_seq.device)
        los_states, nlos_states = [], []
        tau_los_sum  = torch.zeros_like(h_los)
        tau_nlos_sum = torch.zeros_like(h_nlos)

        for t in range(seq_len):
            x_t = x_seq[:, t, :]
            proj_nlos_to_los = self.P_nlos2los(h_nlos)
            proj_los_to_nlos = self.P_los2nlos(h_los)
            g_los  = torch.sigmoid(self.gate_los( torch.cat([h_los,  proj_nlos_to_los], dim=1)))
            g_nlos = torch.sigmoid(self.gate_nlos(torch.cat([h_nlos, proj_los_to_nlos], dim=1)))
            h_los_in  = h_los  + g_los  * proj_nlos_to_los
            h_nlos_in = h_nlos + g_nlos * proj_los_to_nlos
            h_los,  tau_los  = self.cell_los( x_t, h_los_in)
            h_nlos, tau_nlos = self.cell_nlos(x_t, h_nlos_in)
            los_states.append(h_los.unsqueeze(1))
            nlos_states.append(h_nlos.unsqueeze(1))
            tau_los_sum  += tau_los
            tau_nlos_sum += tau_nlos

        los_all  = torch.cat(los_states,  dim=1)
        nlos_all = torch.cat(nlos_states, dim=1)
        tau_los_mean  = tau_los_sum  / seq_len
        tau_nlos_mean = tau_nlos_sum / seq_len
        return los_all, nlos_all, tau_los_mean, tau_nlos_mean

    def _pool_and_fuse(self, los_all, nlos_all):
        h_los_avg  = los_all.mean(dim=1)
        h_nlos_avg = nlos_all.mean(dim=1)
        return torch.cat([h_los_avg, h_nlos_avg], dim=1)

    def forward(self, x_seq):
        los_all, nlos_all, tau_los_mean, tau_nlos_mean = self._run_circuits(x_seq)
        h_fused = self._pool_and_fuse(los_all, nlos_all)
        pred = self.classifier(h_fused)
        return pred, tau_los_mean, tau_nlos_mean

    def embed(self, x_seq):
        """Return 64-dim fused embedding for Stage 2/3."""
        los_all, nlos_all, _, _ = self._run_circuits(x_seq)
        return self._pool_and_fuse(los_all, nlos_all)


print(f"DualCircuit_PI_HLNN_NoFP defined: {sum(p.numel() for p in DualCircuit_PI_HLNN_NoFP().parameters()):,} params")

DualCircuit_PI_HLNN_NoFP defined: 16,897 params

In [64]:
# ==========================================
# LOAD STAGE 1 CONFIG + ENCODER
# ==========================================
_saved = torch.load("stage1_pi_hlnn_no_fp_v3_config.pt", map_location="cpu", weights_only=False)
STAGE1_CONFIG = _saved["config"]
EMBEDDING_DIM = STAGE1_CONFIG['hidden_size'] * 2  # 64
print(f"STAGE1_CONFIG: {STAGE1_CONFIG}")

# Stage 1: Frozen LNN encoder + classifier
encoder = DualCircuit_PI_HLNN_NoFP(
    input_size=STAGE1_CONFIG['input_size'],
    hidden_size=STAGE1_CONFIG['hidden_size'],
    dropout=STAGE1_CONFIG['dropout'],
    ode_unfolds=STAGE1_CONFIG['ode_unfolds'],
).to(device)
encoder.load_state_dict(
    torch.load('stage1_pi_hlnn_no_fp_v3_best.pt', map_location=device, weights_only=True)
)
encoder.eval()
for param in encoder.parameters():
    param.requires_grad = False
print(f"Stage 1: Loaded DualCircuit_PI_HLNN_NoFP from stage1_pi_hlnn_no_fp_v3_best.pt")
print(f"  Params: {sum(p.numel() for p in encoder.parameters()):,} (frozen), Embedding: {EMBEDDING_DIM}-dim")

STAGE1_CONFIG: {'pre_crop': 10, 'post_crop': 50, 'total_len': 60, 'search_start': 740, 'search_end': 810, 'hidden_size': 32, 'input_size': 1, 'dropout': 0.2, 'ode_unfolds': 6, 'batch_size': 64, 'max_epochs': 50, 'lr': 0.001, 'weight_decay': 0.0001, 'warmup_epochs': 3, 'patience': 10, 'grad_clip': 1.0, 'val_ratio': 0.15, 'test_ratio': 0.15, 'seed': 42}
Stage 1: Loaded DualCircuit_PI_HLNN_NoFP from stage1_pi_hlnn_no_fp_v3_best.pt
  Params: 16,897 (frozen), Embedding: 64-dim

---
## Section 2: Load Dataset + Stage 1 Split

Load `combined_uwb_dataset.csv`, preprocess CIR, and apply Stage 1's **70/15/15 stratified split** (seed=42).

This ensures the test set (15%) is truly unseen by all stages.

In [65]:
# ==========================================
# PREPROCESSING (same as Stage 1/2/3)
# ==========================================
def get_roi_alignment(sig, search_start=STAGE1_CONFIG['search_start'],
                      search_end=STAGE1_CONFIG['search_end']):
    """Find leading edge by backtracking from peak."""
    region = sig[search_start:search_end]
    if len(region) == 0:
        return np.argmax(sig)
    peak_local = np.argmax(region)
    peak_idx = search_start + peak_local
    peak_val = sig[peak_idx]
    noise_section = sig[:search_start]
    if len(noise_section) > 10:
        noise_mean = np.mean(noise_section)
        noise_std = np.std(noise_section)
        threshold = max(noise_mean + 3 * noise_std, 0.05 * peak_val)
    else:
        threshold = 0.05 * peak_val
    leading_edge = peak_idx
    for i in range(peak_idx, max(search_start - 20, 0), -1):
        if sig[i] < threshold:
            leading_edge = i + 1
            break
    return leading_edge


def preprocess_cir(sig, leading_edge):
    """Convert RXPACC-normalized CIR to windowed, min-max normalized sequence."""
    PRE = STAGE1_CONFIG['pre_crop']
    TOTAL = STAGE1_CONFIG['total_len']
    start = max(0, leading_edge - PRE)
    end = start + TOTAL
    if end > len(sig):
        end = len(sig)
        start = max(0, end - TOTAL)
    crop = sig[start:end]
    if len(crop) < TOTAL:
        crop = np.pad(crop, (0, TOTAL - len(crop)), mode='constant')
    local_min, local_max = np.min(crop), np.max(crop)
    rng = local_max - local_min
    crop = (crop - local_min) / rng if rng > 0 else np.zeros(TOTAL)
    return crop


# ==========================================
# LOAD COMBINED DATASET
# ==========================================
dataset_path = "../dataset/channels/combined_uwb_dataset.csv"
print(f"Loading: {dataset_path}")
df_all = pd.read_csv(dataset_path)
cir_cols = sorted([c for c in df_all.columns if c.startswith('CIR')],
                  key=lambda x: int(x.replace('CIR', '')))

print(f"  Total samples: {len(df_all)}")
print(f"  LOS: {(df_all['Label']==0).sum()}, NLOS: {(df_all['Label']==1).sum()}")

# Preprocess all samples — extract sigs, metadata, fp_idx, d_hardware
all_sigs, all_les = [], []
all_d_hw, all_d_direct, all_d_bounce, all_labels, all_source = [], [], [], [], []
all_fp_idx = []

for idx, row in df_all.iterrows():
    sig = pd.to_numeric(row[cir_cols], errors='coerce').fillna(0).astype(float).values
    rxpacc = float(row.get('RXPACC', 128.0))
    if rxpacc > 0:
        sig = sig / rxpacc
    le = get_roi_alignment(sig)
    all_sigs.append(sig)
    all_les.append(le)
    all_d_hw.append(float(row['Distance']))
    all_d_direct.append(float(row['d_direct']))
    all_d_bounce.append(float(row['d_bounce']))
    all_labels.append(int(row['Label']))
    all_source.append(str(row.get('Source_File', '')))

    # fp_idx
    fp_i = float(row['FP_INDEX']) / 64.0
    all_fp_idx.append(fp_i)

all_d_hw     = np.array(all_d_hw)
all_d_direct = np.array(all_d_direct)
all_d_bounce = np.array(all_d_bounce)
all_labels   = np.array(all_labels)
all_fp_idx   = np.array(all_fp_idx)

# Compute bounce_path_idx for all samples (per-sample continuous target)
all_bpi = all_fp_idx + (all_d_bounce - all_d_hw) / M_PER_IDX

# Ground truth correctable (from dataset column)
gt_correctable = ((df_all['Label'] == 1) & (df_all['is_correctable'] == 1)).values

# Scenario groups
all_groups = []
for sf in all_source:
    match = re.search(r'([\d.]+)m_(nlos|los)', sf)
    all_groups.append(match.group(1) + 'm_' + match.group(2) if match else 'unknown')
all_groups = np.array(all_groups)

# Preprocess CIR for LNN
total_len = STAGE1_CONFIG['total_len']
cir_sequences = [preprocess_cir(all_sigs[i], all_les[i]) for i in range(len(all_sigs))]
cir_tensor = torch.tensor(
    np.array(cir_sequences).reshape(-1, total_len, 1),
    dtype=torch.float32
).to(device)

# ==========================================
# APPLY STAGE 1's 70/15/15 SPLIT (seed=42)
# ==========================================
indices = np.arange(len(df_all))
idx_train, idx_temp = train_test_split(
    indices, test_size=STAGE1_CONFIG['val_ratio'] + STAGE1_CONFIG['test_ratio'],
    stratify=all_labels, random_state=STAGE1_CONFIG['seed']
)
idx_val, idx_test = train_test_split(
    idx_temp, test_size=STAGE1_CONFIG['test_ratio'] / (STAGE1_CONFIG['val_ratio'] + STAGE1_CONFIG['test_ratio']),
    stratify=all_labels[idx_temp], random_state=STAGE1_CONFIG['seed']
)

print(f"\nStage 1 split (seed={STAGE1_CONFIG['seed']}):")
print(f"  Train: {len(idx_train)} ({100*len(idx_train)/len(df_all):.0f}%)")
print(f"  Val:   {len(idx_val)} ({100*len(idx_val)/len(df_all):.0f}%)")
print(f"  Test:  {len(idx_test)} ({100*len(idx_test)/len(df_all):.0f}%)")
print(f"  Train — LOS: {(all_labels[idx_train]==0).sum()}, NLOS: {(all_labels[idx_train]==1).sum()}")
print(f"  Test  — LOS: {(all_labels[idx_test]==0).sum()}, NLOS: {(all_labels[idx_test]==1).sum()}")
print(f"  Train NLOS correctable: {gt_correctable[idx_train].sum()}")
print(f"  Test  NLOS correctable: {gt_correctable[idx_test].sum()}")

# Show bounce_path_idx stats for NLOS
nlos_mask = all_labels == 1
print(f"\n  bounce_path_idx (NLOS): mean={all_bpi[nlos_mask].mean():.2f}, "
      f"std={all_bpi[nlos_mask].std():.2f}, "
      f"range=[{all_bpi[nlos_mask].min():.2f}, {all_bpi[nlos_mask].max():.2f}]")

Loading: ../dataset/channels/combined_uwb_dataset.csv
  Total samples: 3600
  LOS: 1800, NLOS: 1800

Stage 1 split (seed=42):
  Train: 2520 (70%)
  Val:   540 (15%)
  Test:  540 (15%)
  Train — LOS: 1260, NLOS: 1260
  Test  — LOS: 270, NLOS: 270
  Train NLOS correctable: 361
  Test  NLOS correctable: 68

  bounce_path_idx (NLOS): mean=757.86, std=9.61, range=[735.75, 779.23]

---
## Section 3: Extract Embeddings + Train Stage 2/3 RF

1. Extract 64-dim LNN embeddings from frozen Stage 1 encoder for all combined samples
2. Train Stage 2 RF (correctable classifier) on `idx_train` NLOS — 64 features
3. Train Stage 3 RF (bounce_path_idx regressor) on `idx_train` correctable NLOS — 66 features (64 LNN + fp_idx + d_hw)

In [66]:
# ==========================================
# EXTRACT EMBEDDINGS (all combined samples, once)
# ==========================================
print("Extracting embeddings from frozen Stage 1 encoder...")
all_embeddings = []
BATCH_SIZE = 256
with torch.no_grad():
    for i in range(0, len(cir_tensor), BATCH_SIZE):
        batch = cir_tensor[i:i+BATCH_SIZE]
        emb = encoder.embed(batch)
        all_embeddings.append(emb.cpu().numpy())

embeddings = np.vstack(all_embeddings)
print(f"  Embeddings shape: {embeddings.shape}")

# ==========================================
# STAGE 2: Train RF Classifier on idx_train NLOS (64 features)
# ==========================================
print(f"\n{'='*60}")
print("Stage 2: Train RF Classifier (Correctable vs Challenging)")
print(f"{'='*60}")

train_nlos_mask = np.isin(indices, idx_train) & (all_labels == 1)
train_nlos_idx = np.where(train_nlos_mask)[0]

X_s2_train = embeddings[train_nlos_idx]
y_s2_train = np.where(gt_correctable[train_nlos_idx], 0, 1)  # 0=correctable, 1=challenging

print(f"  Train NLOS samples: {len(train_nlos_idx)}")
print(f"    Correctable (0): {(y_s2_train == 0).sum()}")
print(f"    Challenging (1): {(y_s2_train == 1).sum()}")

stage2_rf = RandomForestClassifier(
    n_estimators=200, max_depth=None, min_samples_split=5, min_samples_leaf=2,
    class_weight="balanced", random_state=STAGE1_CONFIG['seed'], n_jobs=-1,
)
stage2_rf.fit(X_s2_train, y_s2_train)
print(f"  Stage 2 RF trained: {stage2_rf.n_estimators} trees, {stage2_rf.n_features_in_} features")

# ==========================================
# STAGE 3: Train RF Regressor — bounce_path_idx (66 features, combined only)
# Target: bounce_path_idx (per-sample continuous CIR index)
# Features: 64 LNN + fp_idx + d_hardware = 66
# Data: idx_train correctable from combined only
# ==========================================
print(f"\n{'='*60}")
print("Stage 3: Train RF Regressor (bounce_path_idx — combined only)")
print(f"{'='*60}")

# Combined train correctable
train_corr_mask = np.isin(indices, idx_train) & gt_correctable
train_corr_idx = np.where(train_corr_mask)[0]

# Features: 64 LNN + fp_idx + d_hardware (NO SP features)
X_s3_train = np.hstack([
    embeddings[train_corr_idx],
    all_fp_idx[train_corr_idx].reshape(-1, 1),
    all_d_hw[train_corr_idx].reshape(-1, 1)
])
y_s3_train = all_bpi[train_corr_idx]  # bounce_path_idx target
g_s3_train = all_groups[train_corr_idx]

print(f"  Train correctable: {len(train_corr_idx)}")
print(f"  Features: {X_s3_train.shape[1]} (64 LNN + fp_idx + d_hardware)")
print(f"  Target: bounce_path_idx (CIR index, continuous per sample)")
print(f"    bpi range: [{y_s3_train.min():.2f}, {y_s3_train.max():.2f}], "
      f"mean={y_s3_train.mean():.2f}, std={y_s3_train.std():.2f}")

# Inverse-frequency sample weights
unique_groups_s3, group_counts_s3 = np.unique(g_s3_train, return_counts=True)
group_weight_map = {g: len(g_s3_train) / (len(unique_groups_s3) * c)
                    for g, c in zip(unique_groups_s3, group_counts_s3)}
sample_weights = np.array([group_weight_map[g] for g in g_s3_train])

print(f"  Sample weights (inverse-frequency):")
for g in sorted(group_weight_map):
    print(f"    {g}: weight={group_weight_map[g]:.3f} (n={dict(zip(unique_groups_s3, group_counts_s3))[g]})")

stage3_rf = RandomForestRegressor(
    n_estimators=200, max_depth=None, min_samples_split=5, min_samples_leaf=2,
    random_state=STAGE1_CONFIG['seed'], n_jobs=-1,
)
stage3_rf.fit(X_s3_train, y_s3_train, sample_weight=sample_weights)
print(f"  Stage 3 RF trained: {stage3_rf.n_estimators} trees, {stage3_rf.n_features_in_} features")

print(f"\nAll stages ready. Evaluating on test set ({len(idx_test)} combined samples)...")

Extracting embeddings from frozen Stage 1 encoder...
  Embeddings shape: (3600, 64)

============================================================
Stage 2: Train RF Classifier (Correctable vs Challenging)
============================================================
  Train NLOS samples: 1260
    Correctable (0): 361
    Challenging (1): 899
  Stage 2 RF trained: 200 trees, 64 features

============================================================
Stage 3: Train RF Regressor (bounce_path_idx — combined only)
============================================================
  Train correctable: 361
  Features: 66 (64 LNN + fp_idx + d_hardware)
  Target: bounce_path_idx (CIR index, continuous per sample)
    bpi range: [743.36, 779.23], mean=766.40, std=10.82
  Sample weights (inverse-frequency):
    16.09m_nlos: weight=0.549 (n=329)
    9.54m_nlos: weight=5.641 (n=32)
  Stage 3 RF trained: 200 trees, 66 features

All stages ready. Evaluating on test set (540 combined samples)...

---
## Section 4: Chained Pipeline Inference

Stage 1 (LOS/NLOS) → Stage 2 (single-bounce?) → Stage 3 (d_bounce Prediction)

In [67]:
# ==========================================
# TEST SET: Filter arrays to idx_test
# ==========================================
test_cir        = cir_tensor[idx_test]
test_labels     = all_labels[idx_test]
test_d_hw       = all_d_hw[idx_test]
test_d_direct   = all_d_direct[idx_test]
test_d_bounce   = all_d_bounce[idx_test]
test_fp_idx     = all_fp_idx[idx_test]
test_bpi        = all_bpi[idx_test]
test_groups     = all_groups[idx_test]
test_gt_nlos    = test_labels == 1
test_gt_correctable = gt_correctable[idx_test]
test_embeddings = embeddings[idx_test]

n_test = len(idx_test)
print(f"Test set: {n_test} combined samples (LOS: {(~test_gt_nlos).sum()}, NLOS: {test_gt_nlos.sum()})")

# ==========================================
# STAGE 1: LOS/NLOS Classification
# ==========================================
print(f"\nStage 1: LOS/NLOS Classification")
print("=" * 50)

test_probs = []
with torch.no_grad():
    for i in range(0, len(test_cir), BATCH_SIZE):
        batch = test_cir[i:i+BATCH_SIZE]
        pred, _, _ = encoder(batch)
        test_probs.append(pred.cpu().numpy().flatten())

nlos_probs    = np.concatenate(test_probs)
predicted_nlos = nlos_probs >= 0.5
nlos_indices  = np.where(predicted_nlos)[0]

s1_acc = (predicted_nlos == test_gt_nlos).mean()
print(f"  Predicted LOS:  {(~predicted_nlos).sum()}")
print(f"  Predicted NLOS: {predicted_nlos.sum()}")
print(f"  Accuracy: {100*s1_acc:.2f}%")

# ==========================================
# STAGE 2: Correctable vs Challenging (NLOS only)
# ==========================================
print(f"\nStage 2: Single-Bounce Identification")
print("=" * 50)

nlos_embeddings = test_embeddings[nlos_indices]
stage2_preds    = stage2_rf.predict(nlos_embeddings)

correctable_mask = stage2_preds == 0  # 0=correctable
correctable_idx  = nlos_indices[correctable_mask]

print(f"  NLOS samples: {len(nlos_indices)}")
print(f"  Correctable:  {correctable_mask.sum()}")
print(f"  Challenging:  {(~correctable_mask).sum()}")

# ==========================================
# STAGE 3: bounce_path_idx Prediction → d_bounce (66 features)
# Combined pipeline-routed correctable only
# ==========================================
print(f"\nStage 3: bounce_path_idx → d_bounce Prediction")
print("=" * 50)

# Pipeline-routed correctable from combined test set
corr_embeddings = test_embeddings[correctable_idx]
corr_fp_idx     = test_fp_idx[correctable_idx]
corr_d_hw       = test_d_hw[correctable_idx]

# Features: 64 LNN + fp_idx + d_hardware (NO SP features)
X_s3_test = np.hstack([
    corr_embeddings,
    corr_fp_idx.reshape(-1, 1),
    corr_d_hw.reshape(-1, 1)
])

# Predict bounce_path_idx
pred_bpi = stage3_rf.predict(X_s3_test)

# Inverse conversion: d_bounce = d_hardware + (pred_bpi - fp_idx) × M_PER_IDX
pred_d_bounce = corr_d_hw + (pred_bpi - corr_fp_idx) * M_PER_IDX

actual_d_bounce = test_d_bounce[correctable_idx]
actual_bpi      = test_bpi[correctable_idx]
labels_pipe     = test_labels[correctable_idx]
groups_pipe     = test_groups[correctable_idx]
nlos_mask_pipe  = labels_pipe == 1

print(f"  Pipeline funnel: {n_test} → {predicted_nlos.sum()} → {len(correctable_idx)}")
print(f"    Actually NLOS: {nlos_mask_pipe.sum()}, LOS false positives: {(~nlos_mask_pipe).sum()}")

# Filter to actual NLOS only for metrics
predicted_d_bounce = pred_d_bounce[nlos_mask_pipe]
actual_d_bounce_nlos = actual_d_bounce[nlos_mask_pipe]
pred_bpi_nlos = pred_bpi[nlos_mask_pipe]
actual_bpi_nlos = actual_bpi[nlos_mask_pipe]
groups_s3 = groups_pipe[nlos_mask_pipe]

n_s3_total = len(predicted_d_bounce)

# Metrics in d_bounce (meters)
s3_mae  = mean_absolute_error(actual_d_bounce_nlos, predicted_d_bounce)
s3_rmse = np.sqrt(mean_squared_error(actual_d_bounce_nlos, predicted_d_bounce))
s3_r2   = r2_score(actual_d_bounce_nlos, predicted_d_bounce) if n_s3_total > 1 else float('nan')

# Metrics in bounce_path_idx (CIR index units)
bpi_mae  = mean_absolute_error(actual_bpi_nlos, pred_bpi_nlos)
bpi_rmse = np.sqrt(mean_squared_error(actual_bpi_nlos, pred_bpi_nlos))
bpi_r2   = r2_score(actual_bpi_nlos, pred_bpi_nlos) if n_s3_total > 1 else float('nan')

print(f"\n  Stage 3 Results ({n_s3_total} NLOS samples):")
print(f"  --- bounce_path_idx (CIR index) ---")
print(f"    MAE:  {bpi_mae:.4f} idx ({bpi_mae * M_PER_IDX:.4f}m)")
print(f"    RMSE: {bpi_rmse:.4f} idx ({bpi_rmse * M_PER_IDX:.4f}m)")
print(f"    R²:   {bpi_r2:.4f}")
print(f"  --- d_bounce (meters, after inverse conversion) ---")
print(f"    MAE:  {s3_mae:.4f}m")
print(f"    RMSE: {s3_rmse:.4f}m")
print(f"    R²:   {s3_r2:.4f}")
print(f"    Per-scenario:")
for g in sorted(set(groups_s3)):
    mask_g = groups_s3 == g
    if mask_g.sum() > 0:
        mae_g = mean_absolute_error(actual_d_bounce_nlos[mask_g], predicted_d_bounce[mask_g])
        bpi_mae_g = mean_absolute_error(actual_bpi_nlos[mask_g], pred_bpi_nlos[mask_g])
        print(f"      {g}: n={int(mask_g.sum())}, MAE={mae_g:.4f}m (bpi MAE={bpi_mae_g:.4f} idx)")

Test set: 540 combined samples (LOS: 270, NLOS: 270)

Stage 1: LOS/NLOS Classification
==================================================
  Predicted LOS:  263
  Predicted NLOS: 277
  Accuracy: 97.59%

Stage 2: Single-Bounce Identification
==================================================
  NLOS samples: 277
  Correctable:  70
  Challenging:  207

Stage 3: bounce_path_idx → d_bounce Prediction
==================================================
  Pipeline funnel: 540 → 277 → 70
    Actually NLOS: 70, LOS false positives: 0

  Stage 3 Results (70 NLOS samples):
  --- bounce_path_idx (CIR index) ---
    MAE:  1.1583 idx (0.3478m)
    RMSE: 2.3795 idx (0.7146m)
    R²:   0.9520
  --- d_bounce (meters, after inverse conversion) ---
    MAE:  0.3478m
    RMSE: 0.7146m
    R²:   0.5712
    Per-scenario:
      16.09m_nlos: n=68, MAE=0.3529m (bpi MAE=1.1752 idx)
      9.54m_nlos: n=2, MAE=0.1751m (bpi MAE=0.5830 idx)

---
## Section 5: Pipeline Results Table

Display results progressively — Stage 1 → Stage 2 → Stage 3 — each building on the previous DataFrame.

In [68]:
# ==========================================
# Stage 2 metrics (needed for summary)
# ==========================================
gt_corr_at_nlos = test_gt_correctable[nlos_indices].astype(int)
s2_pred_corr    = (stage2_preds == 0).astype(int)
s2_acc  = accuracy_score(gt_corr_at_nlos, s2_pred_corr)
s2_prec = precision_score(gt_corr_at_nlos, s2_pred_corr, zero_division=0)
s2_rec  = recall_score(gt_corr_at_nlos, s2_pred_corr, zero_division=0)
s2_f1   = f1_score(gt_corr_at_nlos, s2_pred_corr, zero_division=0)

# ==========================================
# Build base DataFrame for all test samples
# ==========================================
results = pd.DataFrame()
results['Source_File'] = [all_source[idx_test[i]] for i in range(n_test)]
results['embeddings'] = [list(np.round(test_embeddings[i][:3], 4)) for i in range(n_test)]

# ==========================================
# STAGE 1: Add NLOS_predict column
# ==========================================
results['NLOS_predict'] = np.where(predicted_nlos, 'NLOS', 'LOS')

print(f"Stage 1: LOS/NLOS Classification — {n_test} test samples")
print(f"Accuracy: {100*s1_acc:.2f}%\n")
display(results)

Stage 1: LOS/NLOS Classification — 540 test samples
Accuracy: 97.59%

            Source_File                  embeddings NLOS_predict
0    16.09m_nlos_c5.csv   [-0.1405, -0.002, 0.0295]         NLOS
1      9.29m_los_c2.csv    [-0.1068, 0.0407, 0.009]          LOS
2    16.09m_nlos_c4.csv    [-0.129, 0.0392, 0.0441]         NLOS
3      9.76m_los_c5.csv  [-0.1086, 0.0287, -0.0038]          LOS
4      8.41m_los_c3.csv  [-0.1457, -0.0578, -0.025]          LOS
..                  ...                         ...          ...
535  16.80m_nlos_c4.csv    [-0.068, 0.1098, 0.0289]         NLOS
536    8.41m_los_c7.csv  [-0.1337, -0.023, -0.0094]          LOS
537   9.54m_nlos_c3.csv  [-0.0901, 0.0219, -0.0154]         NLOS
538    9.76m_los_c5.csv   [-0.1081, 0.0363, 0.0044]          LOS
539    9.76m_los_c5.csv    [-0.099, 0.0561, 0.0131]         NLOS

[540 rows x 3 columns]

In [69]:
# ==========================================
# STAGE 2: Add single_bounce column (NLOS samples only)
# ==========================================
results['single_bounce'] = ''
results.loc[predicted_nlos, 'single_bounce'] = np.where(
    stage2_preds == 0, 'single bounce', 'challenging'
)

# Filter to predicted NLOS only, show single bounce first
nlos_results = results[results['NLOS_predict'] == 'NLOS'].copy()
nlos_results = nlos_results.sort_values('single_bounce', ascending=False).reset_index(drop=True)

print(f"Stage 2: Single-Bounce Identification — {len(nlos_results)} NLOS samples")
print(f"Single bounce: {(nlos_results['single_bounce'] == 'single bounce').sum()}, "
      f"Challenging: {(nlos_results['single_bounce'] == 'challenging').sum()}\n")
display(nlos_results)

Stage 2: Single-Bounce Identification — 277 NLOS samples
Single bounce: 70, Challenging: 207

            Source_File                 embeddings NLOS_predict  single_bounce
0    16.09m_nlos_c5.csv  [-0.1405, -0.002, 0.0295]         NLOS  single bounce
1     9.54m_nlos_c4.csv   [-0.1166, 0.027, 0.0199]         NLOS  single bounce
2    16.09m_nlos_c4.csv  [-0.1259, 0.0476, 0.0478]         NLOS  single bounce
3    16.09m_nlos_c5.csv  [-0.1385, 0.0022, 0.0326]         NLOS  single bounce
4    16.09m_nlos_c4.csv  [-0.1297, 0.0313, 0.0377]         NLOS  single bounce
..                  ...                        ...          ...            ...
272  16.09m_nlos_c3.csv  [-0.1105, 0.0637, 0.0433]         NLOS    challenging
273  16.80m_nlos_c1.csv  [-0.1138, 0.0117, 0.0095]         NLOS    challenging
274   9.54m_nlos_c1.csv  [-0.0813, 0.0768, 0.0287]         NLOS    challenging
275  16.80m_nlos_c1.csv    [-0.098, 0.062, 0.0374]         NLOS    challenging
276    9.76m_los_c5.csv   [-0.099, 0.0561, 0.0131]         NLOS    challenging

[277 rows x 4 columns]

In [ ]:
# ==========================================
# STAGE 3: Add d_bounce_predict column (single bounce samples only)
# ==========================================
results['d_bounce_predict'] = np.nan
for i, ci in enumerate(correctable_idx):
    results.loc[ci, 'd_bounce_predict'] = pred_d_bounce[i]

results['error_m'] = results['d_bounce_predict'] - test_d_bounce

sb_results = results[results['d_bounce_predict'].notna()].copy()
sb_results = sb_results[['Source_File', 'embeddings', 
                          'NLOS_predict', 'single_bounce', 'd_bounce_predict', 'error_m']]
sb_results['d_bounce_predict'] = sb_results['d_bounce_predict'].round(4)
sb_results['error_m'] = sb_results['error_m'].round(4)

sb_results['_sort'] = sb_results['Source_File'].str.extract(r'([\d.]+)m')[0].astype(float)
sb_results = sb_results.sort_values('_sort').drop(columns='_sort').reset_index(drop=True)

print(f"Stage 3: d_bounce Prediction — {len(sb_results)} single bounce samples")
print(f"MAE: {s3_mae:.4f}m, RMSE: {s3_rmse:.4f}m\n")
display(sb_results)

Stage 3: d_bounce Prediction — 70 single bounce samples
MAE: 0.3478m, RMSE: 0.7146m

,Source_File,embeddings,NLOS_predict,single_bounce,d_bounce_predict,error_m
0,9.54m_nlos_c4.csv,"[-0.117, 0.0255, 0.0213]",NLOS,single bounce,9.4587,-0.0813
1,9.54m_nlos_c4.csv,"[-0.1166, 0.027, 0.0199]",NLOS,single bounce,9.2711,-0.2689
2,16.09m_nlos_c4.csv,"[-0.1319, 0.0259, 0.0346]",NLOS,single bounce,16.0465,-0.0435
3,16.09m_nlos_c5.csv,"[-0.1405, -0.002, 0.0295]",NLOS,single bounce,16.4433,0.3533
4,16.09m_nlos_c7.csv,"[-0.1323, 0.0386, 0.0507]",NLOS,single bounce,15.9287,-0.1613
...,...,...,...,...,...,...
65,16.09m_nlos_c2.csv,"[-0.1184, 0.0679, 0.0564]",NLOS,single bounce,15.8091,-0.2809
66,16.09m_nlos_c7.csv,"[-0.1334, 0.0415, 0.0518]",NLOS,single bounce,16.0416,-0.0484
67,16.09m_nlos_c2.csv,"[-0.1207, 0.0654, 0.057]",NLOS,single bounce,16.3059,0.2159
68,16.09m_nlos_c7.csv,"[-0.1351, 0.0349, 0.0473]",NLOS,single bounce,15.6874,-0.4026
69,16.09m_nlos_c2.csv,"[-0.1199, 0.0622, 0.0531]",NLOS,single bounce,16.1094,0.0194

---
## Section 6: Summary

In [71]:
print("=" * 60)
print("LNN PIPELINE SUMMARY (Test Set Only)")
print("=" * 60)
print(f"Global split: 70/15/15 (seed={STAGE1_CONFIG['seed']})")
print(f"  Combined: Train={len(idx_train)} | Val={len(idx_val)} | Test={len(idx_test)}")
print(f"Test set: {n_test} combined samples ({test_gt_nlos.sum()} NLOS, {(~test_gt_nlos).sum()} LOS)")
print()

print(f"Stage 1 (LOS/NLOS):")
print(f"  Accuracy: {100*s1_acc:.2f}%  |  Predicted NLOS: {predicted_nlos.sum()}")
print()

print(f"Stage 2 (Correctable Identification):")
print(f"  Accuracy:  {100*s2_acc:.1f}%")
print(f"  Precision: {100*s2_prec:.1f}%")
print(f"  Recall:    {100*s2_rec:.1f}%")
print(f"  F1:        {100*s2_f1:.1f}%")
print(f"  Predicted correctable: {correctable_mask.sum()} / {len(nlos_indices)} NLOS")
print()

print(f"Stage 3 (bounce_path_idx → d_bounce — {stage3_rf.n_features_in_} features):")
print(f"  Pipeline NLOS: {n_s3_total}")
print(f"  Features: 64 LNN + fp_idx + d_hardware = {stage3_rf.n_features_in_}")
print(f"  Target: bounce_path_idx = fp_idx + (d_bounce - d_hardware) / {M_PER_IDX}")
print(f"  Inverse: d_bounce = d_hardware + (pred_bpi - fp_idx) × {M_PER_IDX}")
print()
print(f"  bounce_path_idx metrics:")
print(f"    MAE:  {bpi_mae:.4f} idx = {bpi_mae * M_PER_IDX:.4f}m")
print(f"    RMSE: {bpi_rmse:.4f} idx = {bpi_rmse * M_PER_IDX:.4f}m")
print(f"    R²:   {bpi_r2:.4f}")
print()
print(f"  d_bounce metrics (after inverse conversion):")
print(f"    MAE:  {s3_mae:.4f}m")
print(f"    RMSE: {s3_rmse:.4f}m")
print(f"    R²:   {s3_r2:.4f}")
residuals = predicted_d_bounce - actual_d_bounce_nlos
for tol in [0.25, 0.50, 1.00]:
    pct = 100 * (np.abs(residuals) <= tol).mean()
    print(f"    Within ±{tol:.2f}m: {pct:.1f}%")
print()
print(f"  Per-scenario (±0.50m):")
for g in sorted(set(groups_s3)):
    mask_g = groups_s3 == g
    if mask_g.sum() > 0:
        res_g = predicted_d_bounce[mask_g] - actual_d_bounce_nlos[mask_g]
        correct = int((np.abs(res_g) <= 0.50).sum())
        total   = int(mask_g.sum())
        mae_g   = mean_absolute_error(actual_d_bounce_nlos[mask_g], predicted_d_bounce[mask_g])
        bpi_mae_g = mean_absolute_error(actual_bpi_nlos[mask_g], pred_bpi_nlos[mask_g])
        print(f"    {g}: {correct}/{total} within ±0.5m, MAE={mae_g:.4f}m (bpi={bpi_mae_g:.2f} idx)")
print()
print(f"Encoder: DualCircuit_PI_HLNN_NoFP (v3, {EMBEDDING_DIM}-dim, no FP conditioning)")
print(f"All stages trained on combined dataset only")
print(f"Pipeline: Stage 1 (LNN) → Stage 2 (RF, 64-feat) → Stage 3 (RF, {stage3_rf.n_features_in_}-feat → bpi → d_bounce)")

============================================================
LNN PIPELINE SUMMARY (Test Set Only)
============================================================
Global split: 70/15/15 (seed=42)
  Combined: Train=2520 | Val=540 | Test=540
Test set: 540 combined samples (270 NLOS, 270 LOS)

Stage 1 (LOS/NLOS):
  Accuracy: 97.59%  |  Predicted NLOS: 277

Stage 2 (Correctable Identification):
  Accuracy:  95.7%
  Precision: 90.0%
  Recall:    92.6%
  F1:        91.3%
  Predicted correctable: 70 / 277 NLOS

Stage 3 (bounce_path_idx → d_bounce — 66 features):
  Pipeline NLOS: 70
  Features: 64 LNN + fp_idx + d_hardware = 66
  Target: bounce_path_idx = fp_idx + (d_bounce - d_hardware) / 0.3003
  Inverse: d_bounce = d_hardware + (pred_bpi - fp_idx) × 0.3003

  bounce_path_idx metrics:
    MAE:  1.1583 idx = 0.3478m
    RMSE: 2.3795 idx = 0.7146m
    R²:   0.9520

  d_bounce metrics (after inverse conversion):
    MAE:  0.3478m
    RMSE: 0.7146m
    R²:   0.5712
    Within ±0.25m: 70.0%
    Within ±0.50m: 81.4%
    Within ±1.00m: 90.0%

  Per-scenario (±0.50m):
    16.09m_nlos: 55/68 within ±0.5m, MAE=0.3529m (bpi=1.18 idx)
    9.54m_nlos: 2/2 within ±0.5m, MAE=0.1751m (bpi=0.58 idx)

Encoder: DualCircuit_PI_HLNN_NoFP (v3, 64-dim, no FP conditioning)
All stages trained on combined dataset only
Pipeline: Stage 1 (LNN) → Stage 2 (RF, 64-feat) → Stage 3 (RF, 66-feat → bpi → d_bounce)